# Generated by Django 4.0.3 on 2022-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.IntegerField()),
                ('book_title', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
            ],
        ),
    ]
